spring:
  application:
    name: monew
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true

naver:
  client:
    id: ${NAVER_CLIENT_ID:temp}
    secret: ${NAVER_CLIENT_SECRET:temp}

monew:
  batch:
    news:
      cron: ${NEWS_CRON_TIME:0 0 * * * *}
    notification-cleanup:
      cron: ${NOTIFICATION_CLEANUP_CRON:0 0 3 * * *}
