spring:
  application:
    name: monew
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

naver:
  client:
    id: ${NAVER_CLIENT_ID:temp}
    secret: ${NAVER_CLIENT_SECRET:temp}

monew:
  mongodb:
    enabled: ${MONGODB_ENABLED:false}
  batch:
    news:
      cron: ${NEWS_CRON_TIME:0 0 * * * *}
    user-hard-delete:
      cron: ${USER_HARD_DELETE_CRON_TIME:0 0 3 * * *}
    news-backup:
      cron: ${NEWS_BACKUP_CRON_TIME:0 30 0 * * *}
    notification-cleanup:
      cron: ${NOTIFICATION_CLEANUP_CRON:0 0 3 * * *}
    log-backup:
      cron: ${LOG_BACKUP_CRON_TIME:0 10 0 * * *}

  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:./storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: monew-batch-server
